### ISSUE TITLE
How to restrict to a domain?

### ISSUE THREAD

**Issue by jorgemfm** [trilbymedia/grav-plugin-login-oauth2#1]
Hi,

I've installed and configured oauth2 with google, but how do I resctrict the login to a certain domain? 

I just whant my users to access the website not everyone that has gmail account.

Thank you!

**Comment by w00fz** [comment]
Hello @jorgemfm,

This wasn't taken into consideration at all but that's a really good idea. 

I now added an `Hosted Domain` setting for Google which will allow you to do exactly what you are asking. A new 1.0.1 version has been released and will be available within an hour.

Thanks!

**Comment by jorgemfm** [comment]
Thanks!

I forked the project and made the change myself, was just figuring out how to contribute to the project :D

**Comment by drzraf** [comment]
@w00fz 
`hd` is a nice addition, but is only about fancy Google login form and unrelated to security and authorization. See also https://github.com/thephpleague/oauth2-google/issues/62

Managing domain restrictions means managing **authorization**.

There is a hook for this: `onUserLoginAuthenticate` implemented by `userLoginAuthenticate`.
This hook itself fires `onOAuth2Userdata` and `onOAuth2Username`.
If any of them `throw` an Exception, this results in login being refused (which would be allowed otherwise).

Some observations:
- If my custom authorization plugin is buggy and does not throw it's exception, user are allowed by default. I don't think it's sane when it comes to authorization.
- I understand authorization policies are too complex to be given one unique answer, but providing a default authorization policy that allow to restrict to a list of domain regexp from the UI would fit 99% of use cases and make users happy out of the box.
- Default blueprint provide a `hd: *` directly in the `google` provider instead of under `options`. This is probably an error and may create confusion.
