### ISSUE TITLE
twitter support?

### ISSUE THREAD

**Issue by markcross** [trilbymedia/grav-plugin-login-oauth2#4]
Hi, Is twitter going to go into core of this oauth2 plugin?

Cheers Mark

**Comment by rhukster** [comment]
Twitter actually doesn't support OAuth2, it uses a modified OAuth1 mechanism which is not compatible.  However, I think there's an existing library that has been adapted for the same OAuth2 base library we use, so I do plan on checking it out to see how well it works.

**Comment by rhukster** [comment]
I've looked into this, and even though it's nearly 2019, twitter still doesn't support Oauth2.  It seems they have limited app-only support, but no user authentication.  It seems they shut down every conversation on the topic (https://twittercommunity.com/t/oauth-2-0-support/253c) and have no interest in adding support.  I see no point of creating an Oauth1 plugin solely because Twitter doesn't care about it's end users.

This is clear anyway if you just look at how they continue to restrict their API and stop functionality to enable 3rd party clients.  Really is a shitty service, why do we even use it :)
